// Generated by CoffeeScript 1.10.0
(function() {
  var clickCounter;

  clickCounter = 0;

  $('.signInLocalButton').on('mousedown', function(e) {
    var Buttontext, SubmitText, form, name, text;
    form = $(e.currentTarget.nextElementSibling);
    name = e.currentTarget.nextElementSibling.classList;
    if (name.length === 2) {
      if (clickCounter === 0) {
        Buttontext = $('button').contents().last()[0].textContent;
        $('button').contents().last()[0].textContent = Buttontext.replace("Sign In", "Sign Up");
        SubmitText = $('input[type="submit"]')[0].value;
        $('input[type="submit"]')[0].value = SubmitText.replace('Log In', 'Sign Up');
        form.find('p').prepend('<label class="emailInput">Username </label><input type="text" class="emailInput" name="username">');
        $('.userInfoForm').attr('action', '/register');
        return clickCounter = 1;
      } else {
        $('.emailInput').remove();
        text = $('button').contents().last()[0].textContent;
        $('button').contents().last()[0].textContent = text.replace("Sign Up", "Sign In");
        SubmitText = $('input[type="submit"]')[0].value;
        $('input[type="submit"]')[0].value = SubmitText.replace('Sign Up', 'Log In');
        $('.userInfoForm').attr('action', '/login');
        return clickCounter = 0;
      }
    } else {
      return form.addClass('show');
    }
  });

}).call(this);

//# sourceMappingURL=forms.js.map
