// Generated by CoffeeScript 1.10.0
(function() {
  $(function() {
    var getlocation, location, showPosition;
    location = $('.lat-long');
    $('.get-location').on('click', function(e) {
      return getlocation();
    });
    getlocation = function() {
      if (navigator.geolocation) {
        return navigator.geolocation.getCurrentPosition(showPosition);
      } else {
        return location[0].innerHTML = "Geolocation not supported by browser";
      }
    };
    return showPosition = function(position) {
      var userLocal;
      userLocal = {
        lat: position.coords.latitude,
        long: position.coords.longitude
      };
      location[0].innerHTML = "Lat: " + userLocal.lat + "Long: " + userLocal.long;
      $.post('/weatherMe', {
        data: userLocal,
        dataType: 'json'
      });
    };
  });

}).call(this);

//# sourceMappingURL=weather.js.map
