// Generated by CoffeeScript 1.10.0
(function() {
  $(function() {
    var getlocation, location, showPosition;
    location = $('.lat-long');
    $('.get-location').on('click', function(e) {
      return getlocation();
    });
    getlocation = function() {
      if (navigator.geolocation) {
        navigator.geolocation.watchPosition(showPosition);
      } else {
        location.innerHTML = 'Geolocation is not supported by this browser.';
      }
    };
    return showPosition = function(position) {
      location.innerHTML = 'Latitude: ' + position.coords.latitude + "<br> Longitude: " + position.coords.longitude;
      console.log(position);
    };
  });

}).call(this);

//# sourceMappingURL=weather.js.map
